package org.imat.utile.owl.impl;

import org.imat.utile.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultNoun <br>
 * @version generated on Mon Apr 27 04:17:47 EEST 2015 by lenovo
 */
public class DefaultNoun extends WrappedIndividualImpl implements Noun {

    public DefaultNoun(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#hasSynonym
     */
     
    public Collection<? extends Noun> getHasSynonym() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSYNONYM,
                                               DefaultNoun.class);
        
    }

    public boolean hasHasSynonym() {
	   return !getHasSynonym().isEmpty();
    }

    public void addHasSynonym(Noun newHasSynonym) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSYNONYM,
                                       newHasSynonym);
    }

    public void removeHasSynonym(Noun oldHasSynonym) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSYNONYM,
                                          oldHasSynonym);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isRelatedTo
     */
     
    public Collection<? extends Noun> getIsRelatedTo() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISRELATEDTO,
                                               DefaultNoun.class);
    }

    public boolean hasIsRelatedTo() {
	   return !getIsRelatedTo().isEmpty();
    }

    public void addIsRelatedTo(Noun newIsRelatedTo) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISRELATEDTO,
                                       newIsRelatedTo);
    }

    public void removeIsRelatedTo(Noun oldIsRelatedTo) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISRELATEDTO,
                                          oldIsRelatedTo);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isTypeOf
     */
     
    public Collection<? extends Noun> getIsTypeOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISTYPEOF,
                                               DefaultNoun.class);
    }

    public boolean hasIsTypeOf() {
	   return !getIsTypeOf().isEmpty();
    }

    public void addIsTypeOf(Noun newIsTypeOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISTYPEOF,
                                       newIsTypeOf);
    }

    public void removeIsTypeOf(Noun oldIsTypeOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISTYPEOF,
                                          oldIsTypeOf);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/rami#Label
     */
     
    public Collection<? extends Object> getLabel() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, Object.class);
    }

    public boolean hasLabel() {
		return !getLabel().isEmpty();
    }

    public void addLabel(Object newLabel) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, newLabel);
    }

    public void removeLabel(Object oldLabel) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, oldLabel);
    }


}
