package org.imat.utile.owl.impl;

import org.imat.utile.owl.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultResource <br>
 * @version generated on Mon Apr 27 04:17:47 EEST 2015 by lenovo
 */
public class DefaultResource extends WrappedIndividualImpl implements Resource {

    public DefaultResource(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#hasMethodCall
     */
     
    public Collection<? extends MethodCall> getHasMethodCall() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASMETHODCALL,
                                               DefaultMethodCall.class);
    }

    public boolean hasHasMethodCall() {
	   return !getHasMethodCall().isEmpty();
    }

    public void addHasMethodCall(MethodCall newHasMethodCall) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASMETHODCALL,
                                       newHasMethodCall);
    }

    public void removeHasMethodCall(MethodCall oldHasMethodCall) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASMETHODCALL,
                                          oldHasMethodCall);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isPartOfService
     */
     
    public Collection<? extends Service> getIsPartOfService() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISPARTOFSERVICE,
                                               DefaultService.class);
    }

    public boolean hasIsPartOfService() {
	   return !getIsPartOfService().isEmpty();
    }

    public void addIsPartOfService(Service newIsPartOfService) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISPARTOFSERVICE,
                                       newIsPartOfService);
    }

    public void removeIsPartOfService(Service oldIsPartOfService) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISPARTOFSERVICE,
                                          oldIsPartOfService);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/rami#Label
     */
     
    public Collection<? extends Object> getLabel() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, Object.class);
    }

    public boolean hasLabel() {
		return !getLabel().isEmpty();
    }

    public void addLabel(Object newLabel) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, newLabel);
    }

    public void removeLabel(Object oldLabel) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LABEL, oldLabel);
    }


}
