package org.imat.utile.owl;

import java.io.Serializable;
import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: MethodCall <br>
 * @version generated on Mon Apr 27 04:17:47 EEST 2015 by lenovo
 */

public interface MethodCall extends WrappedIndividual,Serializable {

    /* ***************************************************
     * Property http://www.semanticweb.org/rami#hasInput
     */
     
    /**
     * Gets all property values for the hasInput property.<p>
     * 
     * @returns a collection of values for the hasInput property.
     */
    Collection<? extends InputParam> getHasInput();

    /**
     * Checks if the class has a hasInput property value.<p>
     * 
     * @return true if there is a hasInput property value.
     */
    boolean hasHasInput();

    /**
     * Adds a hasInput property value.<p>
     * 
     * @param newHasInput the hasInput property value to be added
     */
    void addHasInput(InputParam newHasInput);

    /**
     * Removes a hasInput property value.<p>
     * 
     * @param oldHasInput the hasInput property value to be removed.
     */
    void removeHasInput(InputParam oldHasInput);


    /* ***************************************************
     * Property http://www.semanticweb.org/rami#hasOutput
     */
     
    /**
     * Gets all property values for the hasOutput property.<p>
     * 
     * @returns a collection of values for the hasOutput property.
     */
    Collection<? extends OutputParam> getHasOutput();

    /**
     * Checks if the class has a hasOutput property value.<p>
     * 
     * @return true if there is a hasOutput property value.
     */
    boolean hasHasOutput();

    /**
     * Adds a hasOutput property value.<p>
     * 
     * @param newHasOutput the hasOutput property value to be added
     */
    void addHasOutput(OutputParam newHasOutput);

    /**
     * Removes a hasOutput property value.<p>
     * 
     * @param oldHasOutput the hasOutput property value to be removed.
     */
    void removeHasOutput(OutputParam oldHasOutput);


    /* ***************************************************
     * Property http://www.semanticweb.org/rami#isPartOfResource
     */
     
    /**
     * Gets all property values for the isPartOfResource property.<p>
     * 
     * @returns a collection of values for the isPartOfResource property.
     */
    Collection<? extends Resource> getIsPartOfResource();

    /**
     * Checks if the class has a isPartOfResource property value.<p>
     * 
     * @return true if there is a isPartOfResource property value.
     */
    boolean hasIsPartOfResource();

    /**
     * Adds a isPartOfResource property value.<p>
     * 
     * @param newIsPartOfResource the isPartOfResource property value to be added
     */
    void addIsPartOfResource(Resource newIsPartOfResource);

    /**
     * Removes a isPartOfResource property value.<p>
     * 
     * @param oldIsPartOfResource the isPartOfResource property value to be removed.
     */
    void removeIsPartOfResource(Resource oldIsPartOfResource);


    /* ***************************************************
     * Property http://www.semanticweb.org/rami#Label
     */
     
    /**
     * Gets all property values for the Label property.<p>
     * 
     * @returns a collection of values for the Label property.
     */
    Collection<? extends Object> getLabel();

    /**
     * Checks if the class has a Label property value.<p>
     * 
     * @return true if there is a Label property value.
     */
    boolean hasLabel();

    /**
     * Adds a Label property value.<p>
     * 
     * @param newLabel the Label property value to be added
     */
    void addLabel(Object newLabel);

    /**
     * Removes a Label property value.<p>
     * 
     * @param oldLabel the Label property value to be removed.
     */
    void removeLabel(Object oldLabel);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
