package org.imat.utile.owl;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Service <br>
 * @version generated on Mon Apr 27 04:17:47 EEST 2015 by lenovo
 */

public interface Service extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/rami#hasResource
     */
     
    /**
     * Gets all property values for the hasResource property.<p>
     * 
     * @returns a collection of values for the hasResource property.
     */
    Collection<? extends Resource> getHasResource();

    /**
     * Checks if the class has a hasResource property value.<p>
     * 
     * @return true if there is a hasResource property value.
     */
    boolean hasHasResource();

    /**
     * Adds a hasResource property value.<p>
     * 
     * @param newHasResource the hasResource property value to be added
     */
    void addHasResource(Resource newHasResource);

    /**
     * Removes a hasResource property value.<p>
     * 
     * @param oldHasResource the hasResource property value to be removed.
     */
    void removeHasResource(Resource oldHasResource);


    /* ***************************************************
     * Property http://www.semanticweb.org/rami#Label
     */
     
    /**
     * Gets all property values for the Label property.<p>
     * 
     * @returns a collection of values for the Label property.
     */
    Collection<? extends Object> getLabel();

    /**
     * Checks if the class has a Label property value.<p>
     * 
     * @return true if there is a Label property value.
     */
    boolean hasLabel();

    /**
     * Adds a Label property value.<p>
     * 
     * @param newLabel the Label property value to be added
     */
    void addLabel(Object newLabel);

    /**
     * Removes a Label property value.<p>
     * 
     * @param oldLabel the Label property value to be removed.
     */
    void removeLabel(Object oldLabel);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
