package org.imat.utile.owl;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Apr 27 04:17:47 EEST 2015 by lenovo
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/rami#InputParam
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INPUTPARAM.<p>
     * 
     */
    public static final OWLClass CLASS_INPUTPARAM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/rami#InputParam"));

    /* ***************************************************
     * Class http://www.semanticweb.org/rami#MethodCall
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METHODCALL.<p>
     * 
     */
    public static final OWLClass CLASS_METHODCALL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/rami#MethodCall"));

    /* ***************************************************
     * Class http://www.semanticweb.org/rami#Noun
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOUN.<p>
     * 
     */
    public static final OWLClass CLASS_NOUN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/rami#Noun"));

    /* ***************************************************
     * Class http://www.semanticweb.org/rami#OutputParam
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OUTPUTPARAM.<p>
     * 
     */
    public static final OWLClass CLASS_OUTPUTPARAM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/rami#OutputParam"));

    /* ***************************************************
     * Class http://www.semanticweb.org/rami#Parameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/rami#Parameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/rami#Resource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_RESOURCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/rami#Resource"));

    /* ***************************************************
     * Class http://www.semanticweb.org/rami#Service
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SERVICE.<p>
     * 
     */
    public static final OWLClass CLASS_SERVICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/rami#Service"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#hasInput
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASINPUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASINPUT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#hasInput"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#hasMethodCall
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMETHODCALL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMETHODCALL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#hasMethodCall"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#hasOutput
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASOUTPUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASOUTPUT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#hasOutput"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#hasResource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRESOURCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRESOURCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#hasResource"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#hasSynonym
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSYNONYM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSYNONYM = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#hasSynonym"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isEquivalent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISEQUIVALENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISEQUIVALENT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#isEquivalent"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isInputTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISINPUTTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISINPUTTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#isInputTo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isOutputTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISOUTPUTTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISOUTPUTTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#isOutputTo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isPartOfResource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFRESOURCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFRESOURCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#isPartOfResource"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isPartOfService
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFSERVICE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFSERVICE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#isPartOfService"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isRelatedTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRELATEDTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRELATEDTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#isRelatedTo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/rami#isTypeOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISTYPEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISTYPEOF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/rami#isTypeOf"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/rami#Label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LABEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/rami#Label"));


}
